sudo: required

dist: trusty

language: node_js

node_js:
  - "8.3.0"

before_install:
  - docker pull slockit/parity-in3:latest
  - docker run -dti --network="host" -p 8180:8180 -p 8545:8545 -p 8546:8546 slockit/parity-in3:latest --jsonrpc-apis all --logging=3 --jsonrpc-interface=all --ws-interface=all ---chain dev --gas-cap=8000000 --gasprice 0  --reseal-min-period 0   --gas-floor-target 8700000  --tracing on
  - while ! echo exit | nc localhost 8546; do sleep 1; done
  
install:
  - npm install
  - npm run build

services:
  - docker

after_script:
        - scp -i ~/.ssh/travis -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r test/report/* "travis@46.38.250.122:in3-ts/" 

notifications:
  slack:
      rooms:
         - slockitteam:HARkL0L8gSaKg55PNEKFoUWW#prv_code

